"""Live demo: chat with the from-scratch, instruction-tuned model.

Loads the best available checkpoint (DPO > SFT > base) and serves a Gradio UI.
Give it a few words; it writes a short story using them — generated by a 12M
parameter transformer built and trained from scratch in this repo.

    python app.py            # local:  http://127.0.0.1:7860
Deploy: push this repo to a Hugging Face Space (SDK: gradio). Include
out/<ckpt>.pt and data/tokenizer.json.
"""

import os

import torch
import gradio as gr

import chat
from infer import load, chat_generate

OUT_DIR = os.path.join(os.path.dirname(__file__), "out")
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

# pick the most-aligned checkpoint that exists
for _fn in ("dpo.pt", "sft.pt", "ckpt.pt"):
    CKPT = os.path.join(OUT_DIR, _fn)
    if os.path.exists(CKPT):
        break
STAGE = {"dpo.pt": "DPO-aligned", "sft.pt": "SFT", "ckpt.pt": "base (pretrained)"}[_fn]
TOK, MODEL, CFG = load(CKPT, DEVICE)


def write_story(words_str, temperature):
    words = [w.strip().lower() for w in words_str.replace(",", " ").split() if w.strip()]
    if not words:
        return "Enter a word or two first (e.g. `dragon, cake`)."
    prompt = chat.build_prompt(words)
    story = chat_generate(MODEL, TOK, prompt, DEVICE,
                          max_new_tokens=200, temperature=float(temperature), top_k=100)
    hit = chat.word_hit_rate(story, words)
    return f"{story}\n\n— used {int(hit*len(words))}/{len(words)} requested words"


with gr.Blocks(title="GPT From Scratch") as demo:
    gr.Markdown(
        f"# GPT From Scratch — live demo\n"
        f"A **{MODEL.num_params()/1e6:.0f}M-parameter** transformer "
        f"(RoPE · RMSNorm · SwiGLU · GQA) built, pretrained, SFT'd and DPO-aligned "
        f"from scratch — no `transformers`, no pretrained weights. "
        f"Serving the **{STAGE}** checkpoint on `{DEVICE}`.\n\n"
        f"Give it a few words and it writes a short story using them."
    )
    with gr.Row():
        words = gr.Textbox(label="Words", placeholder="dragon, cake, birthday", scale=3)
        temp = gr.Slider(0.2, 1.2, value=0.7, step=0.1, label="Creativity", scale=1)
    btn = gr.Button("Write a story", variant="primary")
    out = gr.Textbox(label="Story", lines=10)
    gr.Examples([["dog, ball, happy"], ["princess, dragon, brave"],
                 ["robot, garden, surprise"], ["boat, storm, friend"]], inputs=words)
    btn.click(write_story, [words, temp], out)
    words.submit(write_story, [words, temp], out)


if __name__ == "__main__":
    demo.launch()
